// import './shared/credentials.js'
import './instagram'
import './background/services/insecure_headers.js'
import './background/services/on_install.js'
import './background/storage/collection.js'
import './background/storage/storage_promise.js'
import './background/storage/instagram_stats.js'
import './background/storage/chrome_history.js'
// import './background/window_confirmator.js'
import './background/main_service.js'
